name: Notify Slack on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  slack_notification:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: 'C059QQDDE2U' # 送信先チャンネルのIDを設定
        run: |
          curl -X POST -H "Authorization: Bearer $SLACK_BOT_TOKEN" -H "Content-type: application/json" \
          --data '{"channel":"'$SLACK_CHANNEL'","text":"<!channel> GIP変更のPRがMergeされました。terraform applyの実行を各自でお願いします。"}' \
          https://slack.com/api/chat.postMessage
